### ISSUE TITLE
Can not install PopV following the tutorial notebook

### ISSUE THREAD

**Issue by Xinlei-Gao** [YosefLab/PopV#31]
Hi there!

Thanks for developing PopV! I would like to run the tutorial notebook to use Tabula sapiens as reference to predict cell types. I opened the notebook 'tabula_sapiens_tutorial.ipynb' in google colab. Code block 1 and block2 run successfully. But when I run code block 3: "!pop install popv", I encountered the following error:

 Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Could you please help me with this issue? Thank you so much!

Best,

Xinlei

**Comment by canergen** [comment]
Thanks for making me aware. PopV doesn't work with python 3.10 as OnClass has outdated requirements (https://github.com/wangshenguiuc/OnClass/issues/9). Colab has in the meantime updated their python version. The best way to fix it would be to update PyPI OnClass version and I contacted their author. I'll give them some days and otherwise make the dependency on OnClass optional (not the best solution but will make it pypi and Colab compatible). For now the best way to install it would be locally using python 3.9.

**Comment by Xinlei-Gao** [comment]
Hi Can,

Thank you for your prompt help! Your proposed solutions sounds great to me.
I will try to install it locally for now and look forward to any updates.

Best regards,

Xinlei

**Comment by canergen** [comment]
Fixed with popV v0.4.1. Thanks for bringing up the issue.

**Comment by Xinlei-Gao** [comment]
Awesome, thanks for the update!
